### ISSUE TITLE
Etkinliklerin Githun reposundan beslenmesi

### ISSUE THREAD

**Issue by vedatmahir** [smtaydemir/chevent#2]
Selamlar Samet, ellerine sağlık, güzel düşünce.

Bu etkinlikleri herhangi bir Github Reposundan okuyacak şekilde düzenlersen daha efektif olacağına eminim. PR açılır, PR'i içeri alırsan etkinlik otomatikman eklenmiş olur.

Geçen günlerde @burakcan'lar framer.parts'ı bu şekilde hazırlamıştı. Şuradan inceleyebilirsin : https://github.com/interacthings/framer-modules-list

**Comment by smtaydemir** [comment]
Süper fikir güncellemede o hale getiricem. Teşekkürler.

**Comment by smtaydemir** [comment]
@vedatmahir selamlar artık pr şeklinde etkinlikler eklenebiliyor https://github.com/smtaydemir/chevent/tree/master/events önerin için çok çok teşekkürler :+1:
